#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        0
bspc config window_gap          14

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

bspc rule -a spotify desktop='^4'

nm-applet &
ibus-daemon -xd
nitrogen --restore
compton &

xinput set-prop "Alps Alps Touchpad" "libinput Natural Scrolling Enabled" 1
xinput set-prop "Alps Alps Touchpad" "libinput Tapping Enabled" 1
